// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFc26Fjm-LDi3Nxg4BJ98zfAGoVrp-hLg',
    appId: '1:510058606288:web:10d6f9c1e7072aab3378d5',
    messagingSenderId: '510058606288',
    projectId: 'hotel-management-90255',
    authDomain: 'hotel-management-90255.firebaseapp.com',
    storageBucket: 'hotel-management-90255.firebasestorage.app',
    measurementId: 'G-GDB0GFH5JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLO72ha1O_wN3F22JUnscVdlfJJVRJYy0',
    appId: '1:510058606288:android:7cd11fc7a9005b7d3378d5',
    messagingSenderId: '510058606288',
    projectId: 'hotel-management-90255',
    storageBucket: 'hotel-management-90255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-6TPzmKrpDwDDFytqYbUbcjMatU085EE',
    appId: '1:510058606288:ios:198daa7a8e5c37d93378d5',
    messagingSenderId: '510058606288',
    projectId: 'hotel-management-90255',
    storageBucket: 'hotel-management-90255.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-6TPzmKrpDwDDFytqYbUbcjMatU085EE',
    appId: '1:510058606288:ios:198daa7a8e5c37d93378d5',
    messagingSenderId: '510058606288',
    projectId: 'hotel-management-90255',
    storageBucket: 'hotel-management-90255.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFc26Fjm-LDi3Nxg4BJ98zfAGoVrp-hLg',
    appId: '1:510058606288:web:58ae1d0afe3a10cf3378d5',
    messagingSenderId: '510058606288',
    projectId: 'hotel-management-90255',
    authDomain: 'hotel-management-90255.firebaseapp.com',
    storageBucket: 'hotel-management-90255.firebasestorage.app',
    measurementId: 'G-QKDCVL76VT',
  );
}
